## merge "other" histograms
mergeDataset = {
    "Scouting" : [
        "ScoutingPFMuons",
        "ScoutingPFRun",
        "ScoutingCaloMuon",
        "ScoutingPFMuon",
        "ScoutingCaloHT",
        "ScoutingPFHT",
        "DataScouting",
        "ScoutingPFCommissioning",
        "ScoutingCaloCommissioning",
    ],
    "Parking" : [
        "ParkingHLTPhysicsTrains",
        "ParkingZeroBiasTrains",
        "ParkingZeroBias",
        "ParkingL1SingleEGer",
        "ParkingL1SingleJet",
        "ParkingL1DoubleEG",
        "ParkingL1SingleMu",
        "ParkingZeroBiasIndiv",
        "ParkingL1SingleTau",
        "ParkingL1HTTer",
        "ParkingL1DoubleIsoTau",
        "ParkingL1SingleEG",
        "ParkingL1TripleMu",
        "ParkingL1DoubleJet",
        "ParkingL1DoubleMu",
        "ParkingCosmicsVirginRaw",
        "ParkingHLTPhysicsIndiv",
        "ParkingL1ETMHF",
        "ParkingBPHPromptCSCS",
        "ParkingHIZeroBias",
        "ParkingHT",
        "ParkingHTto",
        "ParkingHLTPhysics",
        "ParkingScoutingMonitor",
        "ParkingL1MinimumBias",
        "DoubleMuParked",
        "TauParked",
        "HTMHTParked",
        "ParkingMuons",
        "METParked",
        "ZeroBiasParked",
        "HLTPhysicsParked",
        "SinglePhotonParked",
        "MuOniaParked",
        "MultiJet1Parked",
        "ParkingHT450to",
        "ParkingHT470to",
        "ParkingHT410to",
        "ParkingHT430to",
        "ParkingHT500to",
        "ParkingHT550to",
        "VBF1Parked",
        
        ## large rate parking
        "ParkingDoubleMuonLowMass",
        "ParkingBPH",
        "ParkingDoubleElectronLowMass",
        "ParkingVBF",
        "ParkingSingleMuon",
        "ParkingMuon",
        "ParkingHH",
        "ParkingLLP",

        "ParkingLSingleEGer",
        "ParkingLSingleJet",
        "ParkingLDoubleEG",
        "ParkingLSingleMu",
        "ParkingLSingleTau",
        "ParkingLHTTer",
        "ParkingLDoubleIsoTau",
        "ParkingLSingleEG",
        "ParkingLTripleMu",
        "ParkingLDoubleJet",
        "ParkingLDoubleMu",
        "VBFParked",
        "MultiJetParked",
        "ParkingLETMHF",
        "ParkingMonitor",
        "ParkingZeroBiasPONIES",
        "MultiJetParkedns",
        "VBFParkedns",
        "MuOniaParkedns",
        "SinglePhotonParkedns",
        "METParkedns",
        "HTMHTParkedns",
        "TauParkedns",
        "ParkingMonitorns",
        "DoubleMuParkedns",
        "ParkingLMinimumBias",
    ],
    "TOTEM" : [
        "RandomTOTEM",
        "JetsTOTEM",
        "MuonEGammaTOTEM",
        "HFvetoTOTEM",
        "Totem",
        "TOTEM_romanPotsTTBB_", 
        "TOTEM_zeroBias", ##small event size
        "TOTEM_romanPots2_", 
        "TOTEM_minBias", 
        "ToTOTEM", 
        "ZeroBiasTOTEM", 
        "TOTEMMinBias",
        "ZeroBiasTotem",
        "MinimumBiasTotem",
        "TOTEM_romanPots",
        "TOTEM_romanPots_",
        "ToTOTEM_DoubleJet_",
        "LP_RomanPots"
    ],
    "ZeroBias" : [
#        "ZeroBias",
        
        "MinimumBias",
        
        "L1MinimumBias",
        
        "HLTPhysics",
        "HLTPhysicsns", 
        "HLTPhysicsIsolatedBunch", 
        "EphemeralZeroBias",
        "EphemeralHLTPhysics",
        "SpecialHLTPhysics",
        "SpecialRandom",
        "SpecialZeroBias",

        "ZeroBiasPD",
        "ZeroBias8b4e",
        "ZeroBiasNominalTrains",
        "ZeroBiasIsolatedBunches",
        "VRZeroBias",
        "ZeroBiasIsolatedBunch", 
        "ZeroBiasPixelHVScan", 
        "ZeroBiasns", 
        "ZeroBiasHPF", 
        "ZeroBiasBunchTrains", 
        "ZeroBiasVdM", 
        "ZeroBiasFirstBunchInTrain", 
        "ZeroBiasFirstBunchAfterTrain", 

        "ZeroBias_T", 
        "ZeroBiasbe", 
        "LP_ZeroBias", 
        "VirginRawZeroBias", 
        "ZeroBiasAfterIsolatedBunch", 
        "VirginRawLAccept", 
        "HLTPhysicsBunchTrains", 
        "PhysicsDST", 
        "VirginRawHLTPhysics", 

        "LMinimumBiasHF", 
        "LP_MinBias", 
        "MinBiasTesla", 
        "LMinimumBias",
        "MinimumBiasns",
    ],
    
    "NoCollisions" : [
        "ZeroBiasNonColliding",
        "Cosmics",  ##small event size
        "Interfill",  ##small event size
        "EmptyBX",
        "LTechBPTXMinusOnly",
        "LTechBPTXQuiet",
        "LTechBPTXPlusOnly",
        "NoBPTXns",
        "NoBPTX_T",
        "Cosmicsns",
        "ExpressCosmics",
    ],
    "HIon" : [
        "L1AcceptXeXeTest",
        "TestEnablesEcalHcalXeXeTest",
        
        "HIDoubleMuon",
        "HIMinimumBias",
        "HIHardProbes",
        "HIOniaTnP",
        "HIOnia",
        "HIHardProbesPrescaleJets",
        "HIHardProbesPrescaleEGs",
        "HIHardProbesPrescaled",
        "HIHardProbesPeripheral",
        "HITrackerVriginRaw",
        "HIForward",
        "HIExpressPhysics",
        "HIHLTMonitor",
        "HITrackerNZS",
        "HITestRawPrime",
        "HITestRaw",
        "HIRateTest",
        "HITestFull",
        "HITestReduced",
        "HIMinimumBiasReducedFormat",
        "HICosmicsTestXeXeTest",
        "HISingleMuon",
        "HIEmptyBX",
        "HIExpressPhysicsRawPrime",
        "HIHLTPhysics",
        "HIHcalNZS",
        "HIPhysicsRawPrime",
        "HINCaloJets",
        "HINPFJets",
        "HITestVR",
        "HIZeroBias",
        "HeavyFlavor",

        "PPRefZeroBias",
        "PPRefDoubleMuon",
        "PPRefExotica",
        "PPRefHardProbes",
        "PPRefSingleMuon",
        
        "PAZeroBias",
        "PAPhysics",

        "PPJet",
        "PPMuon",
        "PPPhoton",
        "PPMinBias",
        "PPFSQ",
        "LAcceptXeXeTest",

        "HINMuon",
        "HINCaloJetsOther",
        "HINPhoton",
        "HINCaloJet",
        "HINPFJetsOther",
        "HINPFJet",


    ],

    "Errors" : [
        
        "HICosmicsTestXeXeTest-Error",
        
        "ParkingZeroBiasPONIES-Error",
        "ParkingDoubleElectronLowMass-Error",
        "EGamma-Error",
        "CommissioningEGamma-Error",
        "MET-Error",
        "LowEGJet-Error",
        "FSQJet2-Error",
        "HFvetoTOTEM-Error",
        "SingleMuon-Error",
        "IsolatedBunch-Error",
        "Cosmics-Error",
        "MinimumBias-Error",
        "ZeroBias-Error",
        "CommissioningSingleJet-Error",
        "DoubleEG-Error",
        "ParkingHT-Error",
        "CommissioningETM-Error",
        "JetHT-Error",

        "ParkingZeroBiasPONIES2-Error",
        "ParkingZeroBiasPONIES3-Error",
        "AlCaLumiPixels-Error",
        "AlCaPhiSym-Error",
        "Interfill-Error",
        "Commissioning-Error",
        "NoBPTX-Error",
        "HLTPhysicsIsolatedBunch-Error",
        "VirginRawZeroBias-Error",


        "ToTOTEM-Error",
        "Totem-Error",
        "TOTEM_minBias-Error",
        "Jet-Error",
        "LAccept-Error",
        "CastorJets-Error",
        "HcalHPDNoise-Error",
        "FSQJet-Error",
        "LJetHPF-Error",
        "MiniDaq-Error",
        "PAZeroBias-Error",
        "EmptyBX-Error",
        "PAPhysics-Error",
        "LP_RomanPots-Error",
        "VRRandom-Error",
        "FEDMonitor-Error",
        "BTagCSV-Error",
        "StageTest-Error",
        "FSQJets-Error",
        "LP_ExclEGMU-Error",

    ],

    "Others" : [
        "HighMultiplicityEOF", ##large rate, small event size
        "NoBPTX", ##large rate, small event size
    ],

    "Prompt" : [
        
        "LowEGJet",
        "HighEGJet",
        "SingleMuonTnP",
        
        "SingleTrack",
        "HighPtPhoton30AndZ",
        "L1JetHPF", 
        "L1EGHPF", 
        "JetMon", 
        "HighPileUp", 
        "HighPileUpHPF", 
        "LogMonitor", 
        
        "DoubleMuonLowPU",
        "HighPtLowerPhotons",
        "MuonShower",
        "IsolatedBunch",
        
        "ScoutingMonitor",
        "ScoutingPFMonitor",
        
        "SingleMuLowPt",
        "SingleMuHighPt",
        "BTagMu",
        "EGamma",
        "DoubleMuonLowMass",
        "JetMET",
        "Tau",
        "Muon",
        "DisplacedJet",

        "MuOnia",
        "Charmonium",

        "JetHT",
        "HTMHT",
        "MET",
        "BTagCSV",
        "HT",
        "BJetPlusX",
        "MultiJet",

        "TauPlusX",

        "SingleMuon",
        "DoubleMuon",
        "MuonEG",
        "DoubleMu",
        "MuHad",

        "SingleMu",
        "SingleElectron",
        "SinglePhoton",
        "Photon",
        "DoubleEG",
        "ElectronHad",
        "DoublePhoton",
        "DoubleElectron"

        ##0Tesla
        "SingleElectron_0T",
        "JetHT_0T",
        "SinglePhoton_0T",
        "Commissioning_0T",
        "HTMHT_0T",
        "MET_0T",

        "AllPhysics2",
        "FSQJet",
        "Jet",
        "MuEG",
        "ForwardTriggers",
        "PhotonHad",
        "FSQJets",
        "DoublePhotonHighPt",
        "BTag",
        "METBTag",

        "CastorJets",
        "SingleElectron_T",
        "DoubleElectron",
        "SinglePhoton_T",
        "EGMLowPU",
        "JetHT_T",
        "SingleMuon_T",
        "MET_T",
        "AllPhysics",
        "DoubleEG_T",
        "FullTrack",
        "HTMHT_T",
        "DisplacedJet_T",
        "LJetHPF",
        "LEGHPF",
        "MuonEG_T",
        "LMuHPF",
        "LP_LJets",
        "LMu",
        "LEG",
        "ElectronStream",
        "HighPtPhotonAndZ",
        "LP_Jets",
        "LP_ExclEGMU",
        "StageTest",
        "SingleElectronns",
        "SingleMuns",
        "MuOnians",
        "DoublePhotonns",
        "TauPlusXns",
        "MultiJetns",
        "METns",
        "BJetPlusXns",
        "Tauns",
        "SinglePhotonns",
        "JetHTns",
        "DoubleElectronns",
        "HTMHTns",
        "DoubleMuns",
        "ElectronHadns",
        "DoublePhotonHighPtns",
        "PhotonHadns",
        "MuEGns",
        "MuHadns",
        "JetMonns",
        "BTagns",
    ],
    "AlCa" : [
        "AlCaElectron", ##small event size
        "AlCaLowPtJet",
        "AlCaLumiPixelsCountsGated",
        "AlCaLumiPixelsCountsPrompt",
        "AlCaP",
        "AlCaPPSPrompt",
        "AlCaPhiSym",
        "HcalNZS",
        "RPCMonitor",
        "TestEnablesEcalHcal",
        "AlcaLumiPixelsExpress",
        "AlCaLumiPixelsCountsUngated",
        "AlCaPPS",
        "AlCaLumiPixelsXeXeTest",
        "ALCAP",
        "AlCaLumiPixels",
        "TestEnablesEcalHcalDT",
        "EcalLaser",
        "HcalHPDNoise", 

        "HcalNZSns", 
        "HcalNZS_T", 
        "HcalHPDNoise_T", 
        "VirginRawAlCaLumiPixels", 
        "VirginRawHcalNZS", 
        "VirginRawTestEnablesEcalHcal", 
        "HcalHPDNoisens", 
        "VirginRawHcalHPDNoise", 

    ],
    "SmallEventContent" : [
        "LAccept", 
        "L1Accept", ##small event size
        "MiniDaq", 
        "D", 
    ],
    "Reserved" : [
        "ReservedDoubleMuonLowMass", ### to be removed??
    ],
    "DAQTest" : [
        "HIRateRest",
        "RateTestHI",
    ],
    "ToBeRemoved" : [
#        "Fake",
        ## Cosmics
        
        "HLTRAWTest",

#    ],
#    "HIon" : [
        ##Scouting Commissioning
        
        "ParkingMonitor"
        
        "TestEnables", ##small event size

        "CommissioningRawPrime",
        "CommissioningZDC",
        "CommissioningEGamma",
        "CommissioningMuons",
        "CommissioningSingleJet",
        "CommissioningTaus",
        "CommissioningHTT",
        "CommissioningETM",
        "CommissioningDoubleJet",

        "HINMuon_HFveto", 
        "HighMultiplicity", 
        "VRRandom", 

        "ExpressAlignment",

        "Commissioning_T",
        "Commissioning",
        "VirginRawCommissioning",
        "Commissioningns",

        "HLTMonitor",
        "LogMonitorns",
        "FEDMonitorns",

        "TestEnablesTracker",
        "TestEnables",
        "FEDMonitor",
        "DQMOfflinePD"
    ],
}


