## merge "other" histograms
mergeDataset = {
    "Muons" : [
        "SingleMuonTnP",
        "DoubleMuonLowPU",
        "MuonShower",
        "Muon",
        "SingleMuon",
        "DoubleMuon",
        "MuonEG",
        "SingleMuon_T",
        "MuonEG_T",
        "SingleMuLowPt",
        "SingleMuHighPt",
        "BTagMu",
        "SingleMu",
        "MuHad",
        "MuEG",
        "LMuHPF",
        "LMu",
        "LP_ExclEGMU",
        "SingleMuns",
        "DoubleMuns",
        "MuEGns",
        "MuHadns",
        "DoubleMu",
    ],
    "DiMuonLowMass" : [
        "MuOnia",
        "MuOnians",
        "Charmonium",
        "DoubleMuonLowMass",
    ],
    "EGamma" : [
        "LowEGJet",
        "HighEGJet",
        "L1EGHPF", 
#        "EGamma",
        "DoubleEG",
        "EGMLowPU",
        "DoubleEG_T",
        "LEGHPF",
        "LEG",
        "SingleElectron",
        "SinglePhoton",
        "Photon",
        "ElectronHad",
        "DoublePhoton",
        "DoubleElectron"
        "SingleElectron_T",
        "DoubleElectron",
        "SinglePhoton_T",
        "SingleElectronns",
        "DoublePhotonns",
        "ElectronStream",
        "DoubleElectronns",
        "ElectronHadns",
        "SingleElectron_0T",
        "SinglePhoton_0T",
        "HighPtLowerPhotons",
        "PhotonHad",
        "DoublePhotonHighPt",
        "HighPtPhotonAndZ",
        "SinglePhotonns",
        "DoublePhotonHighPtns",
        "PhotonHadns",  
    ],
    "Tau" : [
        "TauPlusX",
        "TauPlusXns",
        "Tauns",
#        "Tau",
    ],
    "JetMET" : [
#        "JetMET",
        "MET",
        "MET_0T",
        "METBTag",
        "MET_T",
        "METns",
        "JetHT",
        "HTMHT",
        "JetHT_0T",
        "HTMHT_0T",
        "HT",
        "JetHT_T",
        "HTMHT_T",
        "JetHTns",
        "HTMHTns",
        "FSQJet",
        "Jet",
        "FSQJets",
        "CastorJets",
        "LJetHPF",
        "LP_LJets",
        "LP_Jets",
        "MultiJetns",
        "BJetPlusXns",
        "JetMonns",
        "MultiJet",
        "L1JetHPF", 
        "JetMon", 
#    ],
#    "BTag" : [
        "BTagCSV",
        "BJetPlusX",
#        "BTag",
        "BTagns",
    ],
    "DisplacedJet" : [
#        "DisplacedJet",
        "DisplacedJet_T",
    ],
    "Misc" : [
        "SingleTrack",
        "HighPtPhoton30AndZ",
        "HighPileUp", 
        "HighPileUpHPF", 
        "LogMonitor", 
        "IsolatedBunch",
        "ScoutingMonitor",
        "ScoutingPFMonitor",
        "Commissioning_0T",
        "AllPhysics2",
        "AllPhysics",
        "FullTrack",
        "StageTest",
        "ForwardTriggers",
    ],
    "Others" : [
    ],
    "Excluded" : [
        "ZeroBias",
        "TOTEM",
        "Parking"
    ],
}

from mergeDataset import mergeDataset as mergeDataset_
for group in mergeDataset_:
    if group != "Prompt":
        for dataset in mergeDataset_[group]:
            mergeDataset["Excluded"].append(dataset)
